/**:
  ros__parameters:
    world_name: "default"
    chassis_controller:
      follow_yaw: false
      follow_yaw_pid:
        p: 2.0
        i: 0.0
        d: 0.0
        imin: -1.0
        imax: 1.0
        cmdmin: -2.0
        cmdmax: 2.0
    gimbal_controller:
      pitch_pid:
        p: 2.0
        i: 0.0
        d: 0.0
        imin: -1.0
        imax: 1.0
        cmdmin: -1.0
        cmdmax: 1.0
      yaw_pid:
        p: 2.0
        i: 0.0
        d: 0.0
        imin: -0.2
        imax: 0.2
        cmdmin: -2.0
        cmdmax: 2.0
